# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
from __future__ import annotations

import warnings

import grpc
from contract import contract_pb2 as contract_dot_contract__pb2

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in contract/contract_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NeoaiWorkflowStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteWorkflow = channel.stream_stream(
            "/NeoaiWorkflow/ExecuteWorkflow",
            request_serializer=contract_dot_contract__pb2.ClientEvent.SerializeToString,
            response_deserializer=contract_dot_contract__pb2.Action.FromString,
            _registered_method=True,
        )
        self.GenerateToken = channel.unary_unary(
            "/NeoaiWorkflow/GenerateToken",
            request_serializer=contract_dot_contract__pb2.GenerateTokenRequest.SerializeToString,
            response_deserializer=contract_dot_contract__pb2.GenerateTokenResponse.FromString,
            _registered_method=True,
        )
        self.ListTools = channel.unary_unary(
            "/NeoaiWorkflow/ListTools",
            request_serializer=contract_dot_contract__pb2.ListToolsRequest.SerializeToString,
            response_deserializer=contract_dot_contract__pb2.ListToolsResponse.FromString,
            _registered_method=True,
        )
        self.ListFlows = channel.unary_unary(
            "/NeoaiWorkflow/ListFlows",
            request_serializer=contract_dot_contract__pb2.ListFlowsRequest.SerializeToString,
            response_deserializer=contract_dot_contract__pb2.ListFlowsResponse.FromString,
            _registered_method=True,
        )


class NeoaiWorkflowServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteWorkflow(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListFlows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NeoaiWorkflowServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteWorkflow": grpc.stream_stream_rpc_method_handler(
            servicer.ExecuteWorkflow,
            request_deserializer=contract_dot_contract__pb2.ClientEvent.FromString,
            response_serializer=contract_dot_contract__pb2.Action.SerializeToString,
        ),
        "GenerateToken": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateToken,
            request_deserializer=contract_dot_contract__pb2.GenerateTokenRequest.FromString,
            response_serializer=contract_dot_contract__pb2.GenerateTokenResponse.SerializeToString,
        ),
        "ListTools": grpc.unary_unary_rpc_method_handler(
            servicer.ListTools,
            request_deserializer=contract_dot_contract__pb2.ListToolsRequest.FromString,
            response_serializer=contract_dot_contract__pb2.ListToolsResponse.SerializeToString,
        ),
        "ListFlows": grpc.unary_unary_rpc_method_handler(
            servicer.ListFlows,
            request_deserializer=contract_dot_contract__pb2.ListFlowsRequest.FromString,
            response_serializer=contract_dot_contract__pb2.ListFlowsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("NeoaiWorkflow", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("NeoaiWorkflow", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class NeoaiWorkflow(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteWorkflow(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/NeoaiWorkflow/ExecuteWorkflow",
            contract_dot_contract__pb2.ClientEvent.SerializeToString,
            contract_dot_contract__pb2.Action.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateToken(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/NeoaiWorkflow/GenerateToken",
            contract_dot_contract__pb2.GenerateTokenRequest.SerializeToString,
            contract_dot_contract__pb2.GenerateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTools(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/NeoaiWorkflow/ListTools",
            contract_dot_contract__pb2.ListToolsRequest.SerializeToString,
            contract_dot_contract__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListFlows(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/NeoaiWorkflow/ListFlows",
            contract_dot_contract__pb2.ListFlowsRequest.SerializeToString,
            contract_dot_contract__pb2.ListFlowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
