version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Can be created via ./setup.sh
      - .env
    ports:
      - "${API_EXTERNAL_PORT:-5001}:${AIGW_FASTAPI__API_PORT}"
      - "${METRICS_EXTERNAL_PORT:-8082}:${AIGW_FASTAPI__METRICS_PORT}"
    hostname: ai-gateway
    volumes:
      - ~/.config/gcloud:/gcloud-config
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcloud-config/application_default_credentials.json
