---
description: Tracks Neoai Workflow User's messages input
internal_events: true
action: message_neoai_workflow
product_group: neoai_workflow
additional_properties:
  label:
    description: Hardcoded string workflow_message_event
  property:
    description: Hardcoded string message_request_by_user_neoai_workflow
  value:
    description: Workflow Id that can be used to connect this event to others that happen when the workflow is completed.
milestone: '17.10'
introduced_by_url: https://gitlab.com/gitlab-org/neoai-workflow/neoai-workflow-service/-/merge_requests/279
tiers:
  - ultimate
