---
description: Tracks when explain vulnerability API is called from GitLab instance
internal_events: true
action: request_explain_vulnerability
product_group: ai_framework
milestone: '17.3'
introduced_by_url: https://github.com/neopilot-ai/neopilot/-/merge_requests/1113
tiers:
  - free
  - premium
  - ultimate
