---
description: Tracks successful Neoai Workflow executions
internal_events: true
action: request_neoai_workflow_success
product_group: neoai_workflow
additional_properties:
  label:
    description: Workflow event type label
  property:
    description: Workflow event type Property
  value:
    description: Workflow Id that can be used to connect this event to others that happen when the workflow is completed.
milestone: '17.6'
introduced_by_url: https://gitlab.com/gitlab-org/neoai-workflow/neoai-workflow-service/-/merge_requests/153
tiers:
  - ultimate
