---
description: Tracks Neoai Workflow retries
internal_events: true
action: retry_request_neoai_workflow
product_group: neoai_workflow
additional_properties:
  label:
    description: Workflow event type label
  property:
    description: Hardcoded string workflow_id
  value:
    description: Workflow Id that can be used to connect this event to others that happen when the workflow is completed.
milestone: '17.8'
introduced_by_url: https://gitlab.com/gitlab-org/neoai-workflow/neoai-workflow-service/-/merge_requests/202
tiers:
  - ultimate
