version: "v1"
environment: ambient
components:
  # Step 1: Fetch and format all MR data
  - name: "build_review_context"
    type: DeterministicStepComponent
    tool_name: "build_review_merge_request_context"
    inputs:
      - from: "context:project_id"
        as: "project_id"
      - from: "context:goal"
        as: "merge_request_iid"
    ui_log_events:
      - "on_tool_execution_success"
      - "on_tool_execution_failed"

  # Step 2: Pre-scan codebase for additional context
  - name: "prescan_codebase"
    type: AgentComponent
    prompt_id: "code_review_prescan"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:project_id"
        as: "project_id"
      - from: "context:goal"
        as: "merge_request_iid"
    toolset:
      - "build_review_merge_request_context"
      - "list_repository_tree"
      - "get_repository_file"
      - "read_file"
      - "find_files"
      - "blob_search"
    ui_log_events:
      - "on_tool_execution_success"
      - "on_tool_execution_failed"
      - "on_agent_final_answer"

  # Step 3: Perform code review
  - name: "perform_code_review"
    type: AgentComponent
    prompt_id: "review_merge_request"
    prompt_version: "^1.4.0"
    inputs:
      - from: "context:build_review_context.tool_responses"
        as: "mr_data"
      - from: "context:prescan_codebase.final_answer"
        as: "codebase_context"
      - from: "context:current_date"
        as: "current_date"
    toolset: []

  # Step 4: Publish code review
  - name: "publish_review"
    type: DeterministicStepComponent
    tool_name: "post_neoai_code_review"
    inputs:
      - from: "context:perform_code_review.final_answer"
        as: "review_output"
      - from: "context:project_id"
        as: "project_id"
      - from: "context:goal"
        as: "merge_request_iid"
    ui_log_events:
      - "on_tool_execution_success"
      - "on_tool_execution_failed"

routers:
  - from: "build_review_context"
    to: "prescan_codebase"
  - from: "prescan_codebase"
    to: "perform_code_review"
  - from: "perform_code_review"
    to: "publish_review"
  - from: "publish_review"
    to: "end"

flow:
  entry_point: "build_review_context"
