version: "v1"
environment: ambient
components:
  - name: "gather_context"
    type: AgentComponent
    prompt_id: "resolve_sast_vulnerability_context"
    prompt_version: "^1.0.0"
    inputs:
      - { from: "context:goal", as: "vulnerability_input" }
      - { from: "context:project_http_url_to_repo", as: "repository_url" }
    toolset: ["get_vulnerability_details", "read_file", "read_files", "grep", "find_files", "list_dir"]

  - name: "execute_fix"
    type: AgentComponent
    prompt_id: "resolve_sast_vulnerability_execution"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:gather_context.final_answer"
        as: "vulnerability_context"
    toolset: ["edit_file", "create_file_with_contents", "read_file", "run_command"]

  - name: "commit_and_open_mr"
    type: OneOffComponent
    prompt_id: "resolve_sast_vulnerability_commit_and_push"
    prompt_version: "^1.0.0"
    max_correction_attempts: 3
    inputs:
      - from: "context:gather_context.final_answer"
        as: "vulnerability_context"
      - from: "context:project_http_url_to_repo"
        as: "repository_url"
      - from: "context:workflow_id"
        as: "workflow_id"
    toolset: ["run_git_command"]

  - name: "check_false_positive"
    type: AgentComponent
    prompt_id: "resolve_sast_check_false_positive"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:commit_and_open_mr.tool_responses"
        as: "git_operations_result"
      - from: "context:project_http_url_to_repo"
        as: "repository_url"
      - from: "context:workflow_id"
        as: "workflow_id"
      - from: "context:gather_context.final_answer"
        as: "vulnerability_context"
    toolset:
      - "get_merge_request"
      - "list_merge_request_diffs"
      - "create_merge_request_note"
      - "update_merge_request"
    ui_log_events:
      - "on_agent_final_answer"
      - "on_tool_execution_success"

  - name: "evaluate_merge_request"
    type: AgentComponent
    prompt_id: "resolve_sast_evaluate_mr_readiness"
    prompt_version: "^1.0.0"
    inputs:
      - from: "context:gather_context.final_answer"
        as: "vulnerability_context"
      - from: "context:execute_fix.final_answer"
        as: "fix_execution_result"
      - from: "context:commit_and_open_mr.tool_responses"
        as: "git_operations_result"
      - from: "context:project_http_url_to_repo"
        as: "repository_url"
      - from: "context:workflow_id"
        as: "workflow_id"
      - from: "context:check_false_positive.final_answer"
        as: "false_positive_check"
    toolset:
      - "get_merge_request"
      - "list_merge_request_diffs"
    ui_log_events:
      - "on_agent_final_answer"
      - "on_tool_execution_success"

routers:
  - from: "gather_context"
    to: "execute_fix"
  - from: "execute_fix"
    to: "commit_and_open_mr"
  - from: "commit_and_open_mr"
    to: "check_false_positive"
  - from: "check_false_positive"
    to: "evaluate_merge_request"
  - from: "evaluate_merge_request"
    to: "end"

flow:
  entry_point: "gather_context"
